name: Build md2nexus
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
permissions:
  contents: write

env:
      CARGO_TERM_COLOR: always

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: create a github release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: md2nexus ${{ github.ref_name }}
          draft: true
          prerelease: false

  build:
    name: build for linux
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: cargo build --release

      - name: write out completions
        run: |
          ./target/release/md2nexus --completions bash > completions.bash
          ./target/release/md2nexus --completions zsh > completions.zsh
          ./target/release/md2nexus --completions fish > completions.fish

      - name: tar it up
        run: |
          tar cf md2nexus_amd64_linux.tar -C target/release md2nexus
          tar f md2nexus_amd64_linux.tar -r completions.bash completions.zsh completions.fish
          gzip md2nexus_amd64_linux.tar

      - name: upload amd64 linux release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.release.outputs.upload_url}}
          asset_path: md2nexus_amd64_linux.tar.gz
          asset_name: md2nexus_amd64_linux.tar.gz
          asset_content_type: application/octet-stream

      - name: Build for arm64
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target aarch64-unknown-linux-gnu

      - name: tar it up
        run: |
          tar cf md2nexus_arm64_linux.tar -C target/release md2nexus
          tar f md2nexus_arm64_linux.tar -r completions.bash completions.zsh completions.fish
          gzip md2nexus_arm64_linux.tar

      - name: upload arm64 linux release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.release.outputs.upload_url}}
          asset_path: md2nexus_arm64_linux.tar.gz
          asset_name: md2nexus_arm64_linux.tar.gz
          asset_content_type: application/octet-stream

  macos:
    name: macos both flavors
    runs-on: macos-latest
    needs: [release]
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: cargo build --release

      - name: write out completions
        run: |
          ./target/release/md2nexus --completions bash > completions.bash
          ./target/release/md2nexus --completions zsh > completions.zsh
          ./target/release/md2nexus --completions fish > completions.fish

      - name: tar up the Mac Intel release
        run: |
          tar cf md2nexus_intel_darwin.tar -C target/release md2nexus
          tar f md2nexus_intel_darwin.tar -r completions.bash completions.zsh completions.fish
          gzip md2nexus_intel_darwin.tar

      - name: upload darwin intel release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.release.outputs.upload_url}}
          asset_path: md2nexus_intel_darwin.tar.gz
          asset_name: md2nexus_intel_darwin.tar.gz
          asset_content_type: application/octet-stream

      - run: rustup target install aarch64-apple-darwin
      - run: cargo build --target aarch64-apple-darwin --release

      - name: tar up the aarch64 release
        run: |
          tar cf md2nexus_aarch64_darwin.tar -C target/release md2nexus
          tar f md2nexus_aarch64_darwin.tar -r completions.bash completions.zsh completions.fish
          gzip md2nexus_aarch64_darwin.tar

      - name: upload darwin m1 release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{needs.release.outputs.upload_url}}
          asset_path: md2nexus_aarch64_darwin.tar.gz
          asset_name: md2nexus_aarch64_darwin.tar.gz
          asset_content_type: application/octet-stream
